class Color:
    USERNAME_FG = 7
    USERNAME_BG = 10
    USERNAME_ROOT_BG = 9

    HOSTNAME_FG = 8
    HOSTNAME_BG = 12

    HOME_SPECIAL_DISPLAY = False
    PATH_BG = 14
    PATH_FG = 8
    CWD_FG = 8
    SEPARATOR_FG = 8

    READONLY_BG = 4
    READONLY_FG = 15

    REPO_CLEAN_BG = 12
    REPO_CLEAN_FG = 8
    REPO_DIRTY_BG = 12
    REPO_DIRTY_FG = 1

    JOBS_FG = 14
    JOBS_BG = 8

    CMD_PASSED_BG = 14
    CMD_PASSED_FG = 8
    CMD_FAILED_BG = 1
    CMD_FAILED_FG = 8

    SVN_CHANGES_BG = REPO_DIRTY_BG
    SVN_CHANGES_FG = REPO_DIRTY_FG

    VIRTUAL_ENV_BG = 4
    VIRTUAL_ENV_FG = 7
